### PR TITLE
Update session.md

### PR DESCRIPTION
**Pull request by ossamamehmood**

### CODE REVIEW

**Review by Maikuolan — CHANGES_REQUESTED** [review]
"For get" should be "To get" ("to" makes more sense than "for", in this context). But, "Forget" actually means something completely different. :-)

**Comment by lablnet** [comment]
@Maikuolan  thanks you so much appreiated
actually @ossamamehmood  is not programmer he is graphic designer so he didnt understand whats going on their sorry

**Comment by Maikuolan** [comment]
No problem. No need to be sorry. Just providing basic advice to help out. :-)

**Comment by lablnet** [comment]
@Maikuolan  yes Thanks and welcome so much

**Pull request merged**
